### ISSUE TITLE
Buffer Overflow Bug

### ISSUE THREAD

**Issue by guyinatuxedo** [w-mj/HttpServer#1]
Hawowo, 

I found a buffa ovafwow in this code base Owo. The i-issue is with the spwintf (`sprintf`) caww in http.c on line 95. The spwintf uses two %s, with it being the diwectowy and the fiwe of whatevew fiwe it is wisting. The destinyation is a stack buffer, and there are nyot sufficient size checks to confirm an ovafwow will not happen (so it can). Thank youwu and have a nyice day!~    ☆*:.｡.o(≧▽≦)o.｡.:*☆

**Comment by w-mj** [comment]
Hi.
Thank you for reading my code and feeding back the bug. As you described, this is a bug and need to be fixed. Actually, the code in this project is full filled unsafe use of C functions. That because this project is just a simple practice when I was learning Linux. I just focusd on linux syscalls but ignored others. And I think this project has no actual value except as a simple example for beginners as me. So I have no plan to fix it now. But if you could be interest in fix it, I will very glad to accept your pull request.
Good luck.
